services:
  - type: web
    name: senselense-backend
    env: python
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: PRESAGE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.6
